name: Request

on:
  schedule:
   - cron: "*/1 * * * *"  

jobs:
  close_pr:
    runs-on: ubuntu-latest
  
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Close Pull Request
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          # Calculate the time difference in seconds
          DIFF=$(expr $(date +%s) - $(date -d "${{ github.event.pull_request.created_at }}" +%s))
          # Convert two days to seconds (2 days * 24 hours * 60 minutes * 60 seconds)
          TWO_DAYS=172800
          if [ $DIFF -gt $TWO_DAYS ]; then
            curl \
              --request PATCH \
              --header "Authorization: Bearer $ACCESS_TOKEN" \
              --header "Accept: application/vnd.github.v3+json" \
              --url "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" \
              --data '{"state": "closed"}'
          fi
